### ISSUE TITLE
Atoms: A Retroactive NFT

### ISSUE THREAD

**Issue by casey** [casey/ideas#1]
## Properties

- Every coinbase transaction has, as an input, an atom. This includes all blocks, including historical blocks.
- Atoms input to a transaction move to the first output.

## TBD

- `split`: An operation to apportion input atoms between outputs, so that you can have multiple input atoms to a transaction, but apportion them between different outputs.
- `transmute`: An operation to associate an atom with a SHA256 hash. Atoms start with no content. Owners can `commit` a hash to an atom. The atom is then considered to have the hash preimage as its content. Atoms can be transmuted at any time to convert them to new uses.

## Benefits

- No premine. It's as if Satoshi added support for NFTs from the beginning. Which [he did](https://github.com/JeremyRubin/satoshis-version/blob/2197a48a1432f567314ce6c6c4be9270518f882e/src/main.cpp#L1227), apparently, but removed before launch.

**Comment by casey** [comment]
@JeremyRubin Yoooo, what do you think?

**Comment by JeremyRubin** [comment]
satoshi did this first; read about atoms lol

**Comment by casey** [comment]
Can you provide a link? Searching for "satoshi atoms" on google doesn't turn up anything useful.

**Comment by casey** [comment]
Found it:

https://github.com/JeremyRubin/satoshis-version/blob/2197a48a1432f567314ce6c6c4be9270518f882e/src/main.cpp#L1227

Seems like an excellent precedent for a retroactive NFT.

Why do atoms have a random integer? Why not just number them sequentially with the block height? If you need randomness, then use the block hash.

**Comment by JeremyRubin** [comment]
no idea

**Comment by casey** [comment]
@JeremyRubin Want to chat more about this? I think it's something that I'd be interested in trying to advance, and possibly funding. It seems really aligned with your interests:

- Could bring NFTs to bitcoin in a way that strikes bitcoiners as fair, and has a chance of developing strong consensus, as long as the creation and transfer rules are fair.
- Strongly aligned with Sapio: People will want to do fun, creative stuff with atoms, and Sapio could seamlessly upgrade individual atoms with new functionality.
- Could be used as a basis for your current NFT project.

**Comment by JeremyRubin** [comment]
i really don't understand the problem you're trying to solve. can you state the issue more clearly?

**Comment by casey** [comment]
The problem I'm trying to solve is how to bring NFTs to Bitcoin. This seems like an interesting way to do it, and one which might be appealing to and accepted by many bitcoiners.

**Comment by casey** [comment]
This way has a few interesting properties:

- Scarcity: There can only be as many NFTs as there are atoms. One atom is created per block, so there's currently ~750k in existence.
- Fair but weird distribution: Atoms effectively already distributed among existing coin holders according to the creation and transfer rules. There is no premine. If these creation and transfer rules strike people as being fair and logical, then they'll be okay with the distribution that results. It is a bit weird that we retroactively assign atoms to coins.

**Comment by casey** [comment]
Wrote a readme: https://github.com/casey/bitcoin-atoms

**Comment by casey** [comment]
This is now ordinals, see ordinals.com and github.com/casey/ord.
